#!/bin/bash

NAME=rtlwifi-new
VERSION=0.6

set -e

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $NAME -v $VERSION --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

if [ -e /etc/modprobe.d/50-rtl8723de.conf ]; then
  rm /etc/modprobe.d/50-rtl8723de.conf
fi

exit 0


